name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get code from repo
      - name: Checkout source code
        uses: actions/checkout@v2
      # Install NodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      # Run npm install
      - name: Install dependencies
        run: npm install
      # Run JS linter
      - name: Lint
        run: npm run lint
      # Run unit tests
      - name: Unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      # Build app
      - name: Build app
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
       # Deploy to Netlify using production secrets
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
